import { Book, Shelves } from './book-shelf';

export const MOCK_DATA: {
  all: Book[];
  shelves: Shelves;
  totalPagesRead: number;
} = {
  totalPagesRead: 6000,
  shelves: {
    toRead: [
      {
        title: 'Secrets of the JavaScript Ninja',
        author: 'John Resig',
        ISBN: '193398869',
        myRating: '0',
        averageRating: '4.21',
        publisher: 'Manning Publications',
        binding: 'Paperback',
        yearPublished: '2013',
        originalPublicationYear: '2008',
        dateRead: '',
        dateAdded: '2021/04/18',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title: 'How to Solve It: A New Aspect of Mathematical Method',
        author: 'George Pólya',
        ISBN: '069111966',
        myRating: '0',
        averageRating: '4.16',
        publisher: 'Princeton University Press',
        binding: 'Paperback',
        yearPublished: '2015',
        originalPublicationYear: '1944',
        dateRead: '',
        dateAdded: '2021/02/06',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title: 'Composing Software',
        author: 'Eric Elliott',
        ISBN: '',
        myRating: '0',
        averageRating: '3.86',
        publisher: 'Leanpub',
        binding: 'ebook',
        yearPublished: '2018',
        originalPublicationYear: '',
        dateRead: '',
        dateAdded: '2020/12/02',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title:
          'The Pyramid Principle: Present Your Thinking So Clearly That the Ideas Jump Off the Page and into th',
        author: 'Barbara Minto',
        ISBN: '1405822147',
        myRating: '0',
        averageRating: '3.86',
        publisher: 'Financial Times/ Prentice Hall',
        binding: 'Hardcover',
        yearPublished: '',
        originalPublicationYear: '',
        dateRead: '',
        dateAdded: '2020/10/09',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title: 'The Tangled Web: A Guide to Securing Modern Web Applications',
        author: 'Michal Zalewski',
        ISBN: '1593273886',
        myRating: '0',
        averageRating: '4.07',
        publisher: 'No Starch Press',
        binding: 'Paperback',
        yearPublished: '2011',
        originalPublicationYear: '2011',
        dateRead: '',
        dateAdded: '2020/09/12',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title:
          'Never Split the Difference: Negotiating As If Your Life Depended On It',
        author: 'Chris Voss',
        ISBN: '0062407805',
        myRating: '0',
        averageRating: '4.37',
        publisher: 'Harper Business',
        binding: 'Hardcover',
        yearPublished: '2016',
        originalPublicationYear: '2016',
        dateRead: '',
        dateAdded: '2020/09/06',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title:
          'The Clean Coder: A Code of Conduct for Professional Programmers',
        author: 'Robert C. Martin',
        ISBN: '0137081073',
        myRating: '0',
        averageRating: '4.28',
        publisher: 'Pearson',
        binding: 'Paperback',
        yearPublished: '2011',
        originalPublicationYear: '2011',
        dateRead: '',
        dateAdded: '2020/09/06',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title:
          'The Phoenix Project: A Novel About IT, DevOps, and Helping Your Business Win',
        author: 'Gene Kim',
        ISBN: '0988262592',
        myRating: '0',
        averageRating: '4.26',
        publisher: 'IT Revolution Press',
        binding: 'Hardcover',
        yearPublished: '2013',
        originalPublicationYear: '2013',
        dateRead: '',
        dateAdded: '2020/09/06',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title: 'High Performance Web Sites',
        author: 'Steve Souders',
        ISBN: '0596529309',
        myRating: '0',
        averageRating: '4.15',
        publisher: "O'Reilly Media",
        binding: 'Paperback',
        yearPublished: '2007',
        originalPublicationYear: '2007',
        dateRead: '',
        dateAdded: '2020/08/23',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title: 'HTTP: The Definitive Guide',
        author: 'David Gourley',
        ISBN: '1565925092',
        myRating: '0',
        averageRating: '4.12',
        publisher: "O'Reilly Media",
        binding: 'Paperback',
        yearPublished: '2002',
        originalPublicationYear: '2002',
        dateRead: '',
        dateAdded: '2020/08/15',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title:
          'Deep Learning with JavaScript: Neural networks in TensorFlow.js',
        author: 'Shanqing Cai',
        ISBN: '1617296171',
        myRating: '0',
        averageRating: '4.57',
        publisher: 'Manning Publications',
        binding: 'Paperback',
        yearPublished: '2020',
        originalPublicationYear: '',
        dateRead: '',
        dateAdded: '2020/07/01',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title: 'How to Win Friends and Influence People',
        author: 'Dale Carnegie',
        ISBN: '',
        myRating: '0',
        averageRating: '4.21',
        publisher: 'Gallery Books',
        binding: 'Paperback',
        yearPublished: '1998',
        originalPublicationYear: '1936',
        dateRead: '',
        dateAdded: '2020/03/01',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title: 'The Shadow of the Wind (The Cemetery of Forgotten Books, #1)',
        author: 'Carlos Ruiz Zafón',
        ISBN: '',
        myRating: '0',
        averageRating: '4.27',
        publisher: 'Penguin Books',
        binding: 'Paperback',
        yearPublished: '2005',
        originalPublicationYear: '2001',
        dateRead: '',
        dateAdded: '2019/11/06',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title:
          'Designing Data Visualizations: Representing Informational Relationships',
        author: 'Noah Iliinsky',
        ISBN: '1449312284',
        myRating: '0',
        averageRating: '3.24',
        publisher: "O'Reilly Media",
        binding: 'Paperback',
        yearPublished: '2011',
        originalPublicationYear: '2011',
        dateRead: '',
        dateAdded: '2019/07/31',
        bookshelves: 'technology, to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title:
          'Architecting Angular Applications with Redux, RxJS, and NgRx: Learn to build Redux style high-performing applications with Angular 6',
        author: 'Christoffer Noring',
        ISBN: '',
        myRating: '0',
        averageRating: '3.80',
        publisher: 'Packt Publishing',
        binding: 'Kindle Edition',
        yearPublished: '2018',
        originalPublicationYear: '',
        dateRead: '',
        dateAdded: '2019/11/03',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title: 'Pro JavaScript Design Patterns',
        author: 'Ross Harmes',
        ISBN: '159059908',
        myRating: '0',
        averageRating: '4.06',
        publisher: 'Apress',
        binding: 'Paperback',
        yearPublished: '2007',
        originalPublicationYear: '2007',
        dateRead: '',
        dateAdded: '2019/08/04',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title:
          'Universal Principles of Design: 100 Ways to Enhance Usability, Influence Perception, Increase Appeal, Make Better Design Decisions, and Teach Through Design',
        author: 'William Lidwell',
        ISBN: '1592530079',
        myRating: '0',
        averageRating: '4.15',
        publisher: 'Rockport Publishers',
        binding: 'Hardcover',
        yearPublished: '2003',
        originalPublicationYear: '2003',
        dateRead: '',
        dateAdded: '2019/07/24',
        bookshelves: 'to-read, technology',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title: 'The Creative Habit: Learn It and Use It for Life',
        author: 'Twyla Tharp',
        ISBN: '0743235274',
        myRating: '4',
        averageRating: '4.04',
        publisher: 'Simon  Schuster',
        binding: 'Paperback',
        yearPublished: '2006',
        originalPublicationYear: '2003',
        dateRead: '',
        dateAdded: '2017/09/09',
        bookshelves: 'to-read',
        myReview: '',
        numberOfPages: 300,
      },
    ],
    currentlyReading: [
      {
        title: 'CSS in Depth',
        author: 'Keith J. Grant',
        ISBN: '1617293458',
        myRating: '0',
        averageRating: '4.59',
        publisher: 'Manning Publications',
        binding: 'Paperback',
        yearPublished: '2018',
        originalPublicationYear: '',
        dateRead: '',
        dateAdded: '2020/10/31',
        bookshelves: 'currently-reading',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title: 'Introduction to Algorithms',
        author: 'Thomas H. Cormen',
        ISBN: '0262032937',
        myRating: '0',
        averageRating: '4.34',
        publisher: 'MIT Press (MA)',
        binding: 'Hardcover',
        yearPublished: '2001',
        originalPublicationYear: '1989',
        dateRead: '',
        dateAdded: '2020/08/15',
        bookshelves: 'currently-reading',
        myReview: '',
        numberOfPages: 300,
      },
    ],
    read: [
      {
        title: 'Refactoring: Improving the Design of Existing Code',
        author: 'Martin Fowler',
        ISBN: '0201485672',
        myRating: '4',
        averageRating: '4.25',
        publisher: 'Addison-Wesley Professional',
        binding: 'Hardcover',
        yearPublished: '1999',
        originalPublicationYear: '1999',
        dateRead: '2021/08/11',
        dateAdded: '2020/09/06',
        bookshelves: '',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title:
          'The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change',
        author: 'Stephen R. Covey',
        ISBN: '0743269519',
        myRating: '5',
        averageRating: '4.13',
        publisher: 'Free Press',
        binding: 'Paperback',
        yearPublished: '2004',
        originalPublicationYear: '1988',
        dateRead: '2021/05/13',
        dateAdded: '2020/10/06',
        bookshelves: '',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title: 'Essential Angular',
        author: 'Victor Savkin',
        ISBN: '1788291042',
        myRating: '0',
        averageRating: '2.67',
        publisher: 'Packt Publishing',
        binding: 'ebook',
        yearPublished: '2017',
        originalPublicationYear: '',
        dateRead: '2020/10/25',
        dateAdded: '2020/10/25',
        bookshelves: '',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title: 'High Performance Browser Networking',
        author: 'Ilya Grigorik',
        ISBN: '',
        myRating: '5',
        averageRating: '4.50',
        publisher: "O'Reilly",
        binding: 'Paperback',
        yearPublished: '2013',
        originalPublicationYear: '2013',
        dateRead: '2020/10/21',
        dateAdded: '2020/05/09',
        bookshelves: '',
        myReview:
          "It's awesome book. Anyone who really cares about network level optimization should read this book. I never thought about the use cases that can harm the mobile users. But with this book one can clearly understand why we should care about the mobile devices in terms of bandwidth. It has great explanation about HTTP 2 which will optimize the application to another level. The examples mentioned in the books are also great. Examples are from real life applications such as how facebook handle chat messaging, how google Hangouts use webRTC etc. I really enjoyed by reading this book",
      },
      {
        title: 'Frontend Architecture for Design Systems',
        author: 'Micah Godbolt',
        ISBN: '9352133366',
        myRating: '4',
        averageRating: '3.39',
        publisher: 'Shroff Publishers & Distributors Pvt Ltd',
        binding: 'Paperback',
        yearPublished: '2016',
        originalPublicationYear: '2015',
        dateRead: '',
        dateAdded: '2019/07/24',
        bookshelves: 'technology',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title: 'The War of Art: Winning the Inner Creative Battle',
        author: 'Steven Pressfield',
        ISBN: '0446691437',
        myRating: '4',
        averageRating: '3.98',
        publisher: 'Warner Books',
        binding: 'Paperback',
        yearPublished: '2003',
        originalPublicationYear: '2002',
        dateRead: '2019/11/06',
        dateAdded: '2019/11/06',
        bookshelves: '',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title: 'Pro TypeScript: Application-Scale JavaScript Development',
        author: 'Steve  Fenton',
        ISBN: '1484232488',
        myRating: '4',
        averageRating: '3.95',
        publisher: 'Apress',
        binding: 'Paperback',
        yearPublished: '2018',
        originalPublicationYear: '2014',
        dateRead: '2019/11/02',
        dateAdded: '2019/07/27',
        bookshelves: '',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title:
          'How to Talk to Anyone, Anytime, Anywhere: The Secrets of Good Communication',
        author: 'Larry King',
        ISBN: '0517223317',
        myRating: '4',
        averageRating: '3.52',
        publisher: 'Gramercy Books',
        binding: 'Hardcover',
        yearPublished: '2004',
        originalPublicationYear: '1994',
        dateRead: '2017/09/09',
        dateAdded: '2017/07/17',
        bookshelves: '',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title: 'The Alchemist',
        author: 'Paulo Coelho',
        ISBN: '0061122416',
        myRating: '4',
        averageRating: '3.89',
        publisher: 'HarperCollins',
        binding: 'Paperback',
        yearPublished: '1993',
        originalPublicationYear: '1988',
        dateRead: '',
        dateAdded: '2019/07/24',
        bookshelves: '',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title:
          'The Obstacle Is the Way: The Timeless Art of Turning Trials into Triumph',
        author: 'Ryan Holiday',
        ISBN: '1591846358',
        myRating: '4',
        averageRating: '4.14',
        publisher: 'Portfolio',
        binding: 'Hardcover',
        yearPublished: '2014',
        originalPublicationYear: '2014',
        dateRead: '',
        dateAdded: '2019/07/24',
        bookshelves: '',
        myReview: '',
        numberOfPages: 300,
      },
      {
        title:
          'TypeScript High Performance: Code for performance, use asynchronous programming, and deliver resources efficiently',
        author: 'Ajinkya Kher',
        ISBN: '',
        myRating: '3',
        averageRating: '3.33',
        publisher: 'Packt Publishing',
        binding: 'Kindle Edition',
        yearPublished: '2017',
        originalPublicationYear: '',
        dateRead: '',
        dateAdded: '2019/07/26',
        bookshelves: '',
        myReview: '',
        numberOfPages: 300,
      },
    ],
  },
  all: [
    {
      title: 'CSS in Depth',
      author: 'Keith J. Grant',
      ISBN: '1617293458',
      myRating: '0',
      averageRating: '4.59',
      publisher: 'Manning Publications',
      binding: 'Paperback',
      yearPublished: '2018',
      originalPublicationYear: '',
      dateRead: '',
      dateAdded: '2020/10/31',
      bookshelves: 'currently-reading',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'Refactoring: Improving the Design of Existing Code',
      author: 'Martin Fowler',
      ISBN: '0201485672',
      myRating: '4',
      averageRating: '4.25',
      publisher: 'Addison-Wesley Professional',
      binding: 'Hardcover',
      yearPublished: '1999',
      originalPublicationYear: '1999',
      dateRead: '2021/08/11',
      dateAdded: '2020/09/06',
      bookshelves: '',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'Secrets of the JavaScript Ninja',
      author: 'John Resig',
      ISBN: '193398869',
      myRating: '0',
      averageRating: '4.21',
      publisher: 'Manning Publications',
      binding: 'Paperback',
      yearPublished: '2013',
      originalPublicationYear: '2008',
      dateRead: '',
      dateAdded: '2021/04/18',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title:
        'The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change',
      author: 'Stephen R. Covey',
      ISBN: '0743269519',
      myRating: '5',
      averageRating: '4.13',
      publisher: 'Free Press',
      binding: 'Paperback',
      yearPublished: '2004',
      originalPublicationYear: '1988',
      dateRead: '2021/05/13',
      dateAdded: '2020/10/06',
      bookshelves: '',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'How to Solve It: A New Aspect of Mathematical Method',
      author: 'George Pólya',
      ISBN: '069111966',
      myRating: '0',
      averageRating: '4.16',
      publisher: 'Princeton University Press',
      binding: 'Paperback',
      yearPublished: '2015',
      originalPublicationYear: '1944',
      dateRead: '',
      dateAdded: '2021/02/06',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'Composing Software',
      author: 'Eric Elliott',
      ISBN: '',
      myRating: '0',
      averageRating: '3.86',
      publisher: 'Leanpub',
      binding: 'ebook',
      yearPublished: '2018',
      originalPublicationYear: '',
      dateRead: '',
      dateAdded: '2020/12/02',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'Essential Angular',
      author: 'Victor Savkin',
      ISBN: '1788291042',
      myRating: '0',
      averageRating: '2.67',
      publisher: 'Packt Publishing',
      binding: 'ebook',
      yearPublished: '2017',
      originalPublicationYear: '',
      dateRead: '2020/10/25',
      dateAdded: '2020/10/25',
      bookshelves: '',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'High Performance Browser Networking',
      author: 'Ilya Grigorik',
      ISBN: '',
      myRating: '5',
      averageRating: '4.50',
      publisher: "O'Reilly",
      binding: 'Paperback',
      yearPublished: '2013',
      originalPublicationYear: '2013',
      dateRead: '2020/10/21',
      dateAdded: '2020/05/09',
      bookshelves: '',
      myReview:
        "It's awesome book. Anyone who really cares about network level optimization should read this book. I never thought about the use cases that can harm the mobile users. But with this book one can clearly understand why we should care about the mobile devices in terms of bandwidth. It has great explanation about HTTP 2 which will optimize the application to another level. The examples mentioned in the books are also great. Examples are from real life applications such as how facebook handle chat messaging, how google Hangouts use webRTC etc. I really enjoyed by reading this book",
    },
    {
      title:
        'The Pyramid Principle: Present Your Thinking So Clearly That the Ideas Jump Off the Page and into th',
      author: 'Barbara Minto',
      ISBN: '1405822147',
      myRating: '0',
      averageRating: '3.86',
      publisher: 'Financial Times/ Prentice Hall',
      binding: 'Hardcover',
      yearPublished: '',
      originalPublicationYear: '',
      dateRead: '',
      dateAdded: '2020/10/09',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'The Tangled Web: A Guide to Securing Modern Web Applications',
      author: 'Michal Zalewski',
      ISBN: '1593273886',
      myRating: '0',
      averageRating: '4.07',
      publisher: 'No Starch Press',
      binding: 'Paperback',
      yearPublished: '2011',
      originalPublicationYear: '2011',
      dateRead: '',
      dateAdded: '2020/09/12',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title:
        'Never Split the Difference: Negotiating As If Your Life Depended On It',
      author: 'Chris Voss',
      ISBN: '0062407805',
      myRating: '0',
      averageRating: '4.37',
      publisher: 'Harper Business',
      binding: 'Hardcover',
      yearPublished: '2016',
      originalPublicationYear: '2016',
      dateRead: '',
      dateAdded: '2020/09/06',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'The Clean Coder: A Code of Conduct for Professional Programmers',
      author: 'Robert C. Martin',
      ISBN: '0137081073',
      myRating: '0',
      averageRating: '4.28',
      publisher: 'Pearson',
      binding: 'Paperback',
      yearPublished: '2011',
      originalPublicationYear: '2011',
      dateRead: '',
      dateAdded: '2020/09/06',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title:
        'The Phoenix Project: A Novel About IT, DevOps, and Helping Your Business Win',
      author: 'Gene Kim',
      ISBN: '0988262592',
      myRating: '0',
      averageRating: '4.26',
      publisher: 'IT Revolution Press',
      binding: 'Hardcover',
      yearPublished: '2013',
      originalPublicationYear: '2013',
      dateRead: '',
      dateAdded: '2020/09/06',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'High Performance Web Sites',
      author: 'Steve Souders',
      ISBN: '0596529309',
      myRating: '0',
      averageRating: '4.15',
      publisher: "O'Reilly Media",
      binding: 'Paperback',
      yearPublished: '2007',
      originalPublicationYear: '2007',
      dateRead: '',
      dateAdded: '2020/08/23',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'Introduction to Algorithms',
      author: 'Thomas H. Cormen',
      ISBN: '0262032937',
      myRating: '0',
      averageRating: '4.34',
      publisher: 'MIT Press (MA)',
      binding: 'Hardcover',
      yearPublished: '2001',
      originalPublicationYear: '1989',
      dateRead: '',
      dateAdded: '2020/08/15',
      bookshelves: 'currently-reading',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'HTTP: The Definitive Guide',
      author: 'David Gourley',
      ISBN: '1565925092',
      myRating: '0',
      averageRating: '4.12',
      publisher: "O'Reilly Media",
      binding: 'Paperback',
      yearPublished: '2002',
      originalPublicationYear: '2002',
      dateRead: '',
      dateAdded: '2020/08/15',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'Deep Learning with JavaScript: Neural networks in TensorFlow.js',
      author: 'Shanqing Cai',
      ISBN: '1617296171',
      myRating: '0',
      averageRating: '4.57',
      publisher: 'Manning Publications',
      binding: 'Paperback',
      yearPublished: '2020',
      originalPublicationYear: '',
      dateRead: '',
      dateAdded: '2020/07/01',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'How to Win Friends and Influence People',
      author: 'Dale Carnegie',
      ISBN: '',
      myRating: '0',
      averageRating: '4.21',
      publisher: 'Gallery Books',
      binding: 'Paperback',
      yearPublished: '1998',
      originalPublicationYear: '1936',
      dateRead: '',
      dateAdded: '2020/03/01',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'Frontend Architecture for Design Systems',
      author: 'Micah Godbolt',
      ISBN: '9352133366',
      myRating: '4',
      averageRating: '3.39',
      publisher: 'Shroff Publishers & Distributors Pvt Ltd',
      binding: 'Paperback',
      yearPublished: '2016',
      originalPublicationYear: '2015',
      dateRead: '',
      dateAdded: '2019/07/24',
      bookshelves: 'technology',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'The Shadow of the Wind (The Cemetery of Forgotten Books, #1)',
      author: 'Carlos Ruiz Zafón',
      ISBN: '',
      myRating: '0',
      averageRating: '4.27',
      publisher: 'Penguin Books',
      binding: 'Paperback',
      yearPublished: '2005',
      originalPublicationYear: '2001',
      dateRead: '',
      dateAdded: '2019/11/06',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title:
        'Designing Data Visualizations: Representing Informational Relationships',
      author: 'Noah Iliinsky',
      ISBN: '1449312284',
      myRating: '0',
      averageRating: '3.24',
      publisher: "O'Reilly Media",
      binding: 'Paperback',
      yearPublished: '2011',
      originalPublicationYear: '2011',
      dateRead: '',
      dateAdded: '2019/07/31',
      bookshelves: 'technology, to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'The War of Art: Winning the Inner Creative Battle',
      author: 'Steven Pressfield',
      ISBN: '0446691437',
      myRating: '4',
      averageRating: '3.98',
      publisher: 'Warner Books',
      binding: 'Paperback',
      yearPublished: '2003',
      originalPublicationYear: '2002',
      dateRead: '2019/11/06',
      dateAdded: '2019/11/06',
      bookshelves: '',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title:
        'Architecting Angular Applications with Redux, RxJS, and NgRx: Learn to build Redux style high-performing applications with Angular 6',
      author: 'Christoffer Noring',
      ISBN: '',
      myRating: '0',
      averageRating: '3.80',
      publisher: 'Packt Publishing',
      binding: 'Kindle Edition',
      yearPublished: '2018',
      originalPublicationYear: '',
      dateRead: '',
      dateAdded: '2019/11/03',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'Pro TypeScript: Application-Scale JavaScript Development',
      author: 'Steve  Fenton',
      ISBN: '1484232488',
      myRating: '4',
      averageRating: '3.95',
      publisher: 'Apress',
      binding: 'Paperback',
      yearPublished: '2018',
      originalPublicationYear: '2014',
      dateRead: '2019/11/02',
      dateAdded: '2019/07/27',
      bookshelves: '',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'Pro JavaScript Design Patterns',
      author: 'Ross Harmes',
      ISBN: '159059908',
      myRating: '0',
      averageRating: '4.06',
      publisher: 'Apress',
      binding: 'Paperback',
      yearPublished: '2007',
      originalPublicationYear: '2007',
      dateRead: '',
      dateAdded: '2019/08/04',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title:
        'How to Talk to Anyone, Anytime, Anywhere: The Secrets of Good Communication',
      author: 'Larry King',
      ISBN: '0517223317',
      myRating: '4',
      averageRating: '3.52',
      publisher: 'Gramercy Books',
      binding: 'Hardcover',
      yearPublished: '2004',
      originalPublicationYear: '1994',
      dateRead: '2017/09/09',
      dateAdded: '2017/07/17',
      bookshelves: '',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'The Alchemist',
      author: 'Paulo Coelho',
      ISBN: '0061122416',
      myRating: '4',
      averageRating: '3.89',
      publisher: 'HarperCollins',
      binding: 'Paperback',
      yearPublished: '1993',
      originalPublicationYear: '1988',
      dateRead: '',
      dateAdded: '2019/07/24',
      bookshelves: '',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title:
        'The Obstacle Is the Way: The Timeless Art of Turning Trials into Triumph',
      author: 'Ryan Holiday',
      ISBN: '1591846358',
      myRating: '4',
      averageRating: '4.14',
      publisher: 'Portfolio',
      binding: 'Hardcover',
      yearPublished: '2014',
      originalPublicationYear: '2014',
      dateRead: '',
      dateAdded: '2019/07/24',
      bookshelves: '',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title:
        'TypeScript High Performance: Code for performance, use asynchronous programming, and deliver resources efficiently',
      author: 'Ajinkya Kher',
      ISBN: '',
      myRating: '3',
      averageRating: '3.33',
      publisher: 'Packt Publishing',
      binding: 'Kindle Edition',
      yearPublished: '2017',
      originalPublicationYear: '',
      dateRead: '',
      dateAdded: '2019/07/26',
      bookshelves: '',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title:
        'Universal Principles of Design: 100 Ways to Enhance Usability, Influence Perception, Increase Appeal, Make Better Design Decisions, and Teach Through Design',
      author: 'William Lidwell',
      ISBN: '1592530079',
      myRating: '0',
      averageRating: '4.15',
      publisher: 'Rockport Publishers',
      binding: 'Hardcover',
      yearPublished: '2003',
      originalPublicationYear: '2003',
      dateRead: '',
      dateAdded: '2019/07/24',
      bookshelves: 'to-read, technology',
      myReview: '',
      numberOfPages: 300,
    },
    {
      title: 'The Creative Habit: Learn It and Use It for Life',
      author: 'Twyla Tharp',
      ISBN: '0743235274',
      myRating: '4',
      averageRating: '4.04',
      publisher: 'Simon  Schuster',
      binding: 'Paperback',
      yearPublished: '2006',
      originalPublicationYear: '2003',
      dateRead: '',
      dateAdded: '2017/09/09',
      bookshelves: 'to-read',
      myReview: '',
      numberOfPages: 300,
    },
  ],
};
