name: Run CI workflow on master
on:
  push:
    branches:
      - 'master'
      - 'release/*.*.*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout [master]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'master'
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install
      - run: npx nx affected --target=format:check --parallel=2
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=build --parallel=3
